name: Deploy DotNet project to Azure Function App

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

    inputs:
      function-app-name:
        type: string
        required: true
      function-project-path:
        type: string
        required: true
      environment:
        type: string
        required: true

concurrency:
  # If multiple merges to main are performed simultaneously, they will just be queued up.
  group: ${{ github.workflow }}-${{ inputs.environment }}-${{ github.ref_name }}

jobs:
  build-and-deploy:
    name: Build and deploy ${{ inputs.function-app-name }} to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: OIDC Login to Azure Public Cloud
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: bash
        run: |
          pushd './${{ inputs.function-project-path }}'
          dotnet build -c Release -o ./output
          popd

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ inputs.function-app-name }}
          package: "${{ inputs.function-project-path }}/output"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
