name: Build infrastructure

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    name: Build infrastructure for ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: OIDC Login to Azure Public Cloud
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Lint Bicep files
        run: az bicep build --file .azure/infrastructure/main.bicep

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout
